### ISSUE TITLE
what is the 'boundary_channels' output by Coordconv and how to use them?

### ISSUE THREAD

**Issue by jlinbb** [protossw512/AdaptiveWingLoss#12]
I have noticed that the FAN returns heatmaps (contains landmarks and boundaries) and the boundary channels. The boundary channels seem to be returned by the Coordconv, should they be something like [[000,111,222,...], [012,012,012,...]] ? while I got some other values after trainning. Should I add some loss for 'boundary channels'?

**Comment by protossw512** [comment]
@jlinbb Sorry for the late reply. The boundary channels predict the boundary of the face, so you have to add a loss on it for training. The code for generating ground truth boundary map will be released.
