### ISSUE TITLE
what is output dimention?

### ISSUE THREAD

**Issue by aligoglos** [protossw512/AdaptiveWingLoss#15]
Its obvious input dimension of model is 256*256.
but it seems output landmarks aren't fit to 256 * 256
for example result of them on image is like this:
![test](https://user-images.githubusercontent.com/3922472/75523709-bf696f00-5a21-11ea-9ffe-7586ba0aa098.png)

**Comment by mustangchavez** [comment]
I had trouble with that at first, too. The output landmarks are 64x64, the architecture of the network uses a lower resolution output than input.

**Comment by aligoglos** [comment]
thanks.
