### ISSUE TITLE
Metrics for COFW dataset, Inter-ocular or Inter-pupil?

### ISSUE THREAD

**Issue by BeierZhu** [protossw512/AdaptiveWingLoss#4]
Hi, In section 7.2,  you announced to use inter-pupil distance for normalization ("For the COFW dataset, we use inter-pupil (distance of eye centers) as the normalization factor".
However, in Table 2, the metric for other previous SOTA methods(Robust face landmark estimation under occlusion, etc,) used inter-ocular distance as the normalization factor. 
Is this a mistype?

**Comment by protossw512** [comment]
@BeierZhu Hi, it is not a mistype, I actually followed an ECCV 2018 paper: [A Deeply-initialized Coarse-to-fine Ensemble of
Regression Trees for Face Alignment](http://openaccess.thecvf.com/content_ECCV_2018/papers/Roberto_Valle_A_Deeply-initialized_Coarse-to-fine_ECCV_2018_paper.pdf)

Please refer to table 3.
