### ISSUE TITLE
Usage of coordconv?

### ISSUE THREAD

**Issue by PlumedSerpent** [protossw512/AdaptiveWingLoss#5]
Hi, in your model arch, you return outputs and boundary_channels with their sizes [B,landmarks+1,W,H] and [B,2,W,H]. I am not familiar with coordconv, should we calculate heatmap between concat([B,landmarks,W,H],[B,1,W,H]) and outputs[i]? If so, why should we return boundary_channels ? Thanks for your reply.

**Comment by protossw512** [comment]
We do not need boundary_channels for inference, but we need for training since it is considered as one of the heatmap channels. A loss is applied to it against the groundtruth boundary channel.
