### ISSUE TITLE
Hi, when will you release the training code.

### ISSUE THREAD

**Issue by Sierkinhane** [protossw512/AdaptiveWingLoss#6]

**Comment by protossw512** [comment]
@Sierkinhane Training code is still under development, I have to clean up all experimental code and reproduce my results after I clean up my code, as am not a fulltime student anymore, please be patient :)

**Comment by Sierkinhane** [comment]
Roger that!

**Comment by John1231983** [comment]
@protossw512 please complete it before eccv deadline then many paper will cite you. :)
